DROP TABLE databasechangelog;
DROP TABLE databasechangeloglock;
DROP TABLE t_inactive_user;
DROP TABLE t_word_knowledge_test_resume;
DROP TABLE t_word_in_bundle;
DROP TABLE t_word_bundle;
DROP TABLE t_word;
DROP TABLE t_user_auth_tokens;
DROP TABLE t_user;
